const php_versions: Array<object> = [
  {
    value: 'php7.2',
    text: 'PHP 7.2',
  },
  {
    value: 'php7.3',
    text: 'PHP 7.3',
  },
  {
    value: 'php7.4',
    text: 'PHP 7.4',
  },
  {
    value: 'php8.0',
    text: 'PHP 8.0',
  },
]

const webservers: Array<object> = [
  {
    text: 'Nginx',
    value: 'nginx',
  },
  {
    text: 'OpenLiteSpeed',
    value: 'openlitespeed',
  },
]

const databases: Array<object> = [
  {
    text: 'MySQL 5.7',
    value: 'mysql',
  },
  {
    text: 'MariaDB 10.3',
    value: 'mariadb',
  },
  {
    text: 'PostgreSQL 10.9',
    value: 'postgresql',
  },
  {
    text: 'PostgreSQL 13',
    value: 'postgresql13',
  },
  {
    text: 'None (do not install a database)',
    value: 'none',
  },
]

const web_application_stacks: Array<object> = [
  {
    value: 'nginx_apache2',
    text: 'NGINX + Apache2 Hybrid (You will be able to use .htaccess)',
  },
  {
    value: 'native_nginx',
    text: "Native NGINX (You won't be able to use .htaccess but it is faster)",
  },
  {
    value: 'nginx_custom',
    text: 'Native NGINX + Custom config (For power user. Manual Nginx implementation)',
  },
]

const web_environments: Array<object> = [
  {
    value: 'production',
    text: 'Production',
  },
  {
    value: 'development',
    text: 'Development',
  },
]

const web_ssl_methods: Array<object> = [
  {
    value: 'basic',
    text: 'Basic (One SSL certificate for all domains on this web app)',
  },
  {
    value: 'advanced',
    text: 'Advanced (Different SSL certificate for every domain on this web app)',
  },
]

const vendor_binaries: Array<object> = [
  {
    value: 'php72',
    text: '/usr/bin/php7.2',
  },
  {
    value: 'php73',
    text: '/usr/bin/php7.3',
  },
  {
    value: 'php74',
    text: '/usr/bin/php7.4',
  },
  {
    value: 'php80',
    text: '/usr/bin/php8.0',
  },
  {
    value: 'node',
    text: '/user/bin/node',
  },
  {
    value: 'bash',
    text: '/bin/bash',
  },
]

const predefined_settings: Array<object> = [
  {
    value: 'e1',
    text: 'Every Minutes',
  },
  {
    value: 'e10',
    text: 'Every 10 Minutes',
  },
  {
    value: 'e30',
    text: 'Every 30 Minutes',
  },
  {
    value: 'eh',
    text: 'Every Hours',
  },
  {
    value: 'mn',
    text: 'All midnight',
  },
  {
    value: 'ed',
    text: 'Every Day',
  },
  {
    value: 'ew',
    text: 'Every Week',
  },
  {
    value: 'em',
    text: 'Every Month',
  },
]

const database_encodings = [
  'big5_chinese_ci',
  'big5_bin',
  'big5_chinese_nopad_ci',
  'big5_nopad_bin',
  'dec8_swedish_ci',
  'dec8_bin',
  'dec8_swedish_nopad_ci',
  'dec8_nopad_bin',
  'cp850_general_ci',
  'cp850_bin',
  'cp850_general_nopad_ci',
  'cp850_nopad_bin',
  'hp8_english_ci',
  'hp8_bin',
  'hp8_english_nopad_ci',
  'hp8_nopad_bin',
  'koi8r_general_ci',
  'koi8r_bin',
  'koi8r_general_nopad_ci',
  'koi8r_nopad_bin',
  'latin1_german1_ci',
  'latin1_swedish_ci',
  'latin1_danish_ci',
  'latin1_german2_ci',
  'latin1_bin',
  'latin1_general_ci',
  'latin1_general_cs',
  'latin1_spanish_ci',
  'latin1_swedish_nopad_ci',
  'latin1_nopad_bin',
  'latin2_czech_cs',
  'latin2_general_ci',
  'latin2_hungarian_ci',
  'latin2_croatian_ci',
  'latin2_bin',
  'latin2_general_nopad_ci',
  'latin2_nopad_bin',
  'swe7_swedish_ci',
  'swe7_bin',
  'swe7_swedish_nopad_ci',
  'swe7_nopad_bin',
  'ascii_general_ci',
  'ascii_bin',
  'ascii_general_nopad_ci',
  'ascii_nopad_bin',
  'ujis_japanese_ci',
  'ujis_bin',
  'ujis_japanese_nopad_ci',
  'ujis_nopad_bin',
  'sjis_japanese_ci',
  'sjis_bin',
  'sjis_japanese_nopad_ci',
  'sjis_nopad_bin',
  'hebrew_general_ci',
  'hebrew_bin',
  'hebrew_general_nopad_ci',
  'hebrew_nopad_bin',
  'tis620_thai_ci',
  'tis620_bin',
  'tis620_thai_nopad_ci',
  'tis620_nopad_bin',
  'euckr_korean_ci',
  'euckr_bin',
  'euckr_korean_nopad_ci',
  'euckr_nopad_bin',
  'koi8u_general_ci',
  'koi8u_bin',
  'koi8u_general_nopad_ci',
  'koi8u_nopad_bin',
  'gb2312_chinese_ci',
  'gb2312_bin',
  'gb2312_chinese_nopad_ci',
  'gb2312_nopad_bin',
  'greek_general_ci',
  'greek_bin',
  'greek_general_nopad_ci',
  'greek_nopad_bin',
  'cp1250_general_ci',
  'cp1250_czech_cs',
  'cp1250_croatian_ci',
  'cp1250_bin',
  'cp1250_polish_ci',
  'cp1250_general_nopad_ci',
  'cp1250_nopad_bin',
  'gbk_chinese_ci',
  'gbk_bin',
  'gbk_chinese_nopad_ci',
  'gbk_nopad_bin',
  'latin5_turkish_ci',
  'latin5_bin',
  'latin5_turkish_nopad_ci',
  'latin5_nopad_bin',
  'armscii8_general_ci',
  'armscii8_bin',
  'armscii8_general_nopad_ci',
  'armscii8_nopad_bin',
  'utf8_general_ci',
  'utf8_bin',
  'utf8_unicode_ci',
  'utf8_icelandic_ci',
  'utf8_latvian_ci',
  'utf8_romanian_ci',
  'utf8_slovenian_ci',
  'utf8_polish_ci',
  'utf8_estonian_ci',
  'utf8_spanish_ci',
  'utf8_swedish_ci',
  'utf8_turkish_ci',
  'utf8_czech_ci',
  'utf8_danish_ci',
  'utf8_lithuanian_ci',
  'utf8_slovak_ci',
  'utf8_spanish2_ci',
  'utf8_roman_ci',
  'utf8_persian_ci',
  'utf8_esperanto_ci',
  'utf8_hungarian_ci',
  'utf8_sinhala_ci',
  'utf8_german2_ci',
  'utf8_croatian_mysql561_ci',
  'utf8_unicode_520_ci',
  'utf8_vietnamese_ci',
  'utf8_general_mysql500_ci',
  'utf8_croatian_ci',
  'utf8_myanmar_ci',
  'utf8_thai_520_w2',
  'utf8_general_nopad_ci',
  'utf8_nopad_bin',
  'utf8_unicode_nopad_ci',
  'utf8_unicode_520_nopad_ci',
  'ucs2_general_ci',
  'ucs2_bin',
  'ucs2_unicode_ci',
  'ucs2_icelandic_ci',
  'ucs2_latvian_ci',
  'ucs2_romanian_ci',
  'ucs2_slovenian_ci',
  'ucs2_polish_ci',
  'ucs2_estonian_ci',
  'ucs2_spanish_ci',
  'ucs2_swedish_ci',
  'ucs2_turkish_ci',
  'ucs2_czech_ci',
  'ucs2_danish_ci',
  'ucs2_lithuanian_ci',
  'ucs2_slovak_ci',
  'ucs2_spanish2_ci',
  'ucs2_roman_ci',
  'ucs2_persian_ci',
  'ucs2_esperanto_ci',
  'ucs2_hungarian_ci',
  'ucs2_sinhala_ci',
  'ucs2_german2_ci',
  'ucs2_croatian_mysql561_ci',
  'ucs2_unicode_520_ci',
  'ucs2_vietnamese_ci',
  'ucs2_general_mysql500_ci',
  'ucs2_croatian_ci',
  'ucs2_myanmar_ci',
  'ucs2_thai_520_w2',
  'ucs2_general_nopad_ci',
  'ucs2_nopad_bin',
  'ucs2_unicode_nopad_ci',
  'ucs2_unicode_520_nopad_ci',
  'cp866_general_ci',
  'cp866_bin',
  'cp866_general_nopad_ci',
  'cp866_nopad_bin',
  'keybcs2_general_ci',
  'keybcs2_bin',
  'keybcs2_general_nopad_ci',
  'keybcs2_nopad_bin',
  'macce_general_ci',
  'macce_bin',
  'macce_general_nopad_ci',
  'macce_nopad_bin',
  'macroman_general_ci',
  'macroman_bin',
  'macroman_general_nopad_ci',
  'macroman_nopad_bin',
  'cp852_general_ci',
  'cp852_bin',
  'cp852_general_nopad_ci',
  'cp852_nopad_bin',
  'latin7_estonian_cs',
  'latin7_general_ci',
  'latin7_general_cs',
  'latin7_bin',
  'latin7_general_nopad_ci',
  'latin7_nopad_bin',
  'utf8mb4_general_ci',
  'utf8mb4_bin',
  'utf8mb4_unicode_ci',
  'utf8mb4_icelandic_ci',
  'utf8mb4_latvian_ci',
  'utf8mb4_romanian_ci',
  'utf8mb4_slovenian_ci',
  'utf8mb4_polish_ci',
  'utf8mb4_estonian_ci',
  'utf8mb4_spanish_ci',
  'utf8mb4_swedish_ci',
  'utf8mb4_turkish_ci',
  'utf8mb4_czech_ci',
  'utf8mb4_danish_ci',
  'utf8mb4_lithuanian_ci',
  'utf8mb4_slovak_ci',
  'utf8mb4_spanish2_ci',
  'utf8mb4_roman_ci',
  'utf8mb4_persian_ci',
  'utf8mb4_esperanto_ci',
  'utf8mb4_hungarian_ci',
  'utf8mb4_sinhala_ci',
  'utf8mb4_german2_ci',
  'utf8mb4_croatian_mysql561_ci',
  'utf8mb4_unicode_520_ci',
  'utf8mb4_vietnamese_ci',
  'utf8mb4_croatian_ci',
  'utf8mb4_myanmar_ci',
  'utf8mb4_thai_520_w2',
  'utf8mb4_general_nopad_ci',
  'utf8mb4_nopad_bin',
  'utf8mb4_unicode_nopad_ci',
  'utf8mb4_unicode_520_nopad_ci',
  'cp1251_bulgarian_ci',
  'cp1251_ukrainian_ci',
  'cp1251_bin',
  'cp1251_general_ci',
  'cp1251_general_cs',
  'cp1251_nopad_bin',
  'cp1251_general_nopad_ci',
  'utf16_general_ci',
  'utf16_bin',
  'utf16_unicode_ci',
  'utf16_icelandic_ci',
  'utf16_latvian_ci',
  'utf16_romanian_ci',
  'utf16_slovenian_ci',
  'utf16_polish_ci',
  'utf16_estonian_ci',
  'utf16_spanish_ci',
  'utf16_swedish_ci',
  'utf16_turkish_ci',
  'utf16_czech_ci',
  'utf16_danish_ci',
  'utf16_lithuanian_ci',
  'utf16_slovak_ci',
  'utf16_spanish2_ci',
  'utf16_roman_ci',
  'utf16_persian_ci',
  'utf16_esperanto_ci',
  'utf16_hungarian_ci',
  'utf16_sinhala_ci',
  'utf16_german2_ci',
  'utf16_croatian_mysql561_ci',
  'utf16_unicode_520_ci',
  'utf16_vietnamese_ci',
  'utf16_croatian_ci',
  'utf16_myanmar_ci',
  'utf16_thai_520_w2',
  'utf16_general_nopad_ci',
  'utf16_nopad_bin',
  'utf16_unicode_nopad_ci',
  'utf16_unicode_520_nopad_ci',
  'utf16le_general_ci',
  'utf16le_bin',
  'utf16le_general_nopad_ci',
  'utf16le_nopad_bin',
  'cp1256_general_ci',
  'cp1256_bin',
  'cp1256_general_nopad_ci',
  'cp1256_nopad_bin',
  'cp1257_lithuanian_ci',
  'cp1257_bin',
  'cp1257_general_ci',
  'cp1257_nopad_bin',
  'cp1257_general_nopad_ci',
  'utf32_general_ci',
  'utf32_bin',
  'utf32_unicode_ci',
  'utf32_icelandic_ci',
  'utf32_latvian_ci',
  'utf32_romanian_ci',
  'utf32_slovenian_ci',
  'utf32_polish_ci',
  'utf32_estonian_ci',
  'utf32_spanish_ci',
  'utf32_swedish_ci',
  'utf32_turkish_ci',
  'utf32_czech_ci',
  'utf32_danish_ci',
  'utf32_lithuanian_ci',
  'utf32_slovak_ci',
  'utf32_spanish2_ci',
  'utf32_roman_ci',
  'utf32_persian_ci',
  'utf32_esperanto_ci',
  'utf32_hungarian_ci',
  'utf32_sinhala_ci',
  'utf32_german2_ci',
  'utf32_croatian_mysql561_ci',
  'utf32_unicode_520_ci',
  'utf32_vietnamese_ci',
  'utf32_croatian_ci',
  'utf32_myanmar_ci',
  'utf32_thai_520_w2',
  'utf32_general_nopad_ci',
  'utf32_nopad_bin',
  'utf32_unicode_nopad_ci',
  'utf32_unicode_520_nopad_ci',
  'binary',
  'geostd8_general_ci',
  'geostd8_bin',
  'geostd8_general_nopad_ci',
  'geostd8_nopad_bin',
  'cp932_japanese_ci',
  'cp932_bin',
  'cp932_japanese_nopad_ci',
  'cp932_nopad_bin',
  'eucjpms_japanese_ci',
  'eucjpms_bin',
  'eucjpms_japanese_nopad_ci',
  'eucjpms_nopad_bin',
]

const countries = [
  { v: 'AF', t: 'Afghanistan' },
  { v: 'AX', t: 'Aland Islands' },
  { v: 'AL', t: 'Albania' },
  { v: 'DZ', t: 'Algeria' },
  { v: 'AS', t: 'American Samoa' },
  { v: 'AD', t: 'Andorra' },
  { v: 'AO', t: 'Angola' },
  { v: 'AI', t: 'Anguilla' },
  { v: 'AQ', t: 'Antarctica' },
  { v: 'AG', t: 'Antigua and Barbuda' },
  { v: 'AR', t: 'Argentina' },
  { v: 'AM', t: 'Armenia' },
  { v: 'AW', t: 'Aruba' },
  { v: 'AU', t: 'Australia' },
  { v: 'AT', t: 'Austria' },
  { v: 'AZ', t: 'Azerbaijan' },
  { v: 'BS', t: 'Bahamas' },
  { v: 'BH', t: 'Bahrain' },
  { v: 'BD', t: 'Bangladesh' },
  { v: 'BB', t: 'Barbados' },
  { v: 'BY', t: 'Belarus' },
  { v: 'BE', t: 'Belgium' },
  { v: 'BZ', t: 'Belize' },
  { v: 'BJ', t: 'Benin' },
  { v: 'BM', t: 'Bermuda' },
  { v: 'BT', t: 'Bhutan' },
  { v: 'BO', t: 'Bolivia, Plurinational State of' },
  { v: 'BQ', t: 'Bonaire, Sint Eustatius and Saba' },
  { v: 'BA', t: 'Bosnia and Herzegovina' },
  { v: 'BW', t: 'Botswana' },
  { v: 'BV', t: 'Bouvet Island' },
  { v: 'BR', t: 'Brazil' },
  { v: 'IO', t: 'British Indian Ocean Territory' },
  { v: 'BN', t: 'Brunei Darussalam' },
  { v: 'BG', t: 'Bulgaria' },
  { v: 'BF', t: 'Burkina Faso' },
  { v: 'BI', t: 'Burundi' },
  { v: 'KH', t: 'Cambodia' },
  { v: 'CM', t: 'Cameroon' },
  { v: 'CA', t: 'Canada' },
  { v: 'CV', t: 'Cape Verde' },
  { v: 'KY', t: 'Cayman Islands' },
  { v: 'CF', t: 'Central African Republic' },
  { v: 'TD', t: 'Chad' },
  { v: 'CL', t: 'Chile' },
  { v: 'CN', t: 'China' },
  { v: 'CX', t: 'Christmas Island' },
  { v: 'CC', t: 'Cocos (Keeling) Islands' },
  { v: 'CO', t: 'Colombia' },
  { v: 'KM', t: 'Comoros' },
  { v: 'CG', t: 'Congo' },
  { v: 'CD', t: 'Congo, the Democratic Republic of the' },
  { v: 'CK', t: 'Cook Islands' },
  { v: 'CR', t: 'Costa Rica' },
  { v: 'CI', t: "Côte d'Ivoire" },
  { v: 'HR', t: 'Croatia' },
  { v: 'CU', t: 'Cuba' },
  { v: 'CW', t: 'Curaçao' },
  { v: 'CY', t: 'Cyprus' },
  { v: 'CZ', t: 'Czech Republic' },
  { v: 'DK', t: 'Denmark' },
  { v: 'DJ', t: 'Djibouti' },
  { v: 'DM', t: 'Dominica' },
  { v: 'DO', t: 'Dominican Republic' },
  { v: 'EC', t: 'Ecuador' },
  { v: 'EG', t: 'Egypt' },
  { v: 'SV', t: 'El Salvador' },
  { v: 'GQ', t: 'Equatorial Guinea' },
  { v: 'ER', t: 'Eritrea' },
  { v: 'EE', t: 'Estonia' },
  { v: 'ET', t: 'Ethiopia' },
  { v: 'FK', t: 'Falkland Islands (Malvinas)' },
  { v: 'FO', t: 'Faroe Islands' },
  { v: 'FJ', t: 'Fiji' },
  { v: 'FI', t: 'Finland' },
  { v: 'FR', t: 'France' },
  { v: 'GF', t: 'French Guiana' },
  { v: 'PF', t: 'French Polynesia' },
  { v: 'TF', t: 'French Southern Territories' },
  { v: 'GA', t: 'Gabon' },
  { v: 'GM', t: 'Gambia' },
  { v: 'GE', t: 'Georgia' },
  { v: 'DE', t: 'Germany' },
  { v: 'GH', t: 'Ghana' },
  { v: 'GI', t: 'Gibraltar' },
  { v: 'GR', t: 'Greece' },
  { v: 'GL', t: 'Greenland' },
  { v: 'GD', t: 'Grenada' },
  { v: 'GP', t: 'Guadeloupe' },
  { v: 'GU', t: 'Guam' },
  { v: 'GT', t: 'Guatemala' },
  { v: 'GG', t: 'Guernsey' },
  { v: 'GN', t: 'Guinea' },
  { v: 'GW', t: 'Guinea-Bissau' },
  { v: 'GY', t: 'Guyana' },
  { v: 'HT', t: 'Haiti' },
  { v: 'HM', t: 'Heard Island and McDonald Islands' },
  { v: 'VA', t: 'Holy See (Vatican City State)' },
  { v: 'HN', t: 'Honduras' },
  { v: 'HK', t: 'Hong Kong' },
  { v: 'HU', t: 'Hungary' },
  { v: 'IS', t: 'Iceland' },
  { v: 'IN', t: 'India' },
  { v: 'ID', t: 'Indonesia' },
  { v: 'IR', t: 'Iran, Islamic Republic of' },
  { v: 'IQ', t: 'Iraq' },
  { v: 'IE', t: 'Ireland' },
  { v: 'IM', t: 'Isle of Man' },
  { v: 'IL', t: 'Israel' },
  { v: 'IT', t: 'Italy' },
  { v: 'JM', t: 'Jamaica' },
  { v: 'JP', t: 'Japan' },
  { v: 'JE', t: 'Jersey' },
  { v: 'JO', t: 'Jordan' },
  { v: 'KZ', t: 'Kazakhstan' },
  { v: 'KE', t: 'Kenya' },
  { v: 'KI', t: 'Kiribati' },
  { v: 'KP', t: "Korea, Democratic People's Republic of" },
  { v: 'KW', t: 'Kuwait' },
  { v: 'KG', t: 'Kyrgyzstan' },
  { v: 'LA', t: "Lao People's Democratic Republic" },
  { v: 'LV', t: 'Latvia' },
  { v: 'LB', t: 'Lebanon' },
  { v: 'LS', t: 'Lesotho' },
  { v: 'LR', t: 'Liberia' },
  { v: 'LY', t: 'Libya' },
  { v: 'LI', t: 'Liechtenstein' },
  { v: 'LT', t: 'Lithuania' },
  { v: 'LU', t: 'Luxembourg' },
  { v: 'MO', t: 'Macao' },
  { v: 'MK', t: 'Macedonia, the former Yugoslav Republic of' },
  { v: 'MG', t: 'Madagascar' },
  { v: 'MW', t: 'Malawi' },
  { v: 'MY', t: 'Malaysia' },
  { v: 'MV', t: 'Maldives' },
  { v: 'ML', t: 'Mali' },
  { v: 'MT', t: 'Malta' },
  { v: 'MH', t: 'Marshall Islands' },
  { v: 'MQ', t: 'Martinique' },
  { v: 'MR', t: 'Mauritania' },
  { v: 'MU', t: 'Mauritius' },
  { v: 'YT', t: 'Mayotte' },
  { v: 'MX', t: 'Mexico' },
  { v: 'FM', t: 'Micronesia, Federated States of' },
  { v: 'MD', t: 'Moldova, Republic of' },
  { v: 'MC', t: 'Monaco' },
  { v: 'MN', t: 'Mongolia' },
  { v: 'ME', t: 'Montenegro' },
  { v: 'MS', t: 'Montserrat' },
  { v: 'MA', t: 'Morocco' },
  { v: 'MZ', t: 'Mozambique' },
  { v: 'MM', t: 'Myanmar' },
  { v: 'NA', t: 'Namibia' },
  { v: 'NR', t: 'Nauru' },
  { v: 'NP', t: 'Nepal' },
  { v: 'NL', t: 'Netherlands' },
  { v: 'NC', t: 'New Caledonia' },
  { v: 'NZ', t: 'New Zealand' },
  { v: 'NI', t: 'Nicaragua' },
  { v: 'NE', t: 'Niger' },
  { v: 'NG', t: 'Nigeria' },
  { v: 'NU', t: 'Niue' },
  { v: 'NF', t: 'Norfolk Island' },
  { v: 'MP', t: 'Northern Mariana Islands' },
  { v: 'NO', t: 'Norway' },
  { v: 'OM', t: 'Oman' },
  { v: 'PK', t: 'Pakistan' },
  { v: 'PW', t: 'Palau' },
  { v: 'PS', t: 'Palestinian Territory, Occupied' },
  { v: 'PA', t: 'Panama' },
  { v: 'PG', t: 'Papua New Guinea' },
  { v: 'PY', t: 'Paraguay' },
  { v: 'PE', t: 'Peru' },
  { v: 'PH', t: 'Philippines' },
  { v: 'PN', t: 'Pitcairn' },
  { v: 'PL', t: 'Poland' },
  { v: 'PT', t: 'Portugal' },
  { v: 'PR', t: 'Puerto Rico' },
  { v: 'QA', t: 'Qatar' },
  { v: 'RE', t: 'Réunion' },
  { v: 'RO', t: 'Romania' },
  { v: 'RU', t: 'Russian Federation' },
  { v: 'RW', t: 'Rwanda' },
  { v: 'BL', t: 'Saint Barthélemy' },
  { v: 'SH', t: 'Saint Helena, Ascension and Tristan da Cunha' },
  { v: 'KN', t: 'Saint Kitts and Nevis' },
  { v: 'LC', t: 'Saint Lucia' },
  { v: 'MF', t: 'Saint Martin (French part)' },
  { v: 'PM', t: 'Saint Pierre and Miquelon' },
  { v: 'VC', t: 'Saint Vincent and the Grenadines' },
  { v: 'WS', t: 'Samoa' },
  { v: 'SM', t: 'San Marino' },
  { v: 'ST', t: 'Sao Tome and Principe' },
  { v: 'SA', t: 'Saudi Arabia' },
  { v: 'SN', t: 'Senegal' },
  { v: 'RS', t: 'Serbia' },
  { v: 'SC', t: 'Seychelles' },
  { v: 'SL', t: 'Sierra Leone' },
  { v: 'SG', t: 'Singapore' },
  { v: 'SX', t: 'Sint Maarten (Dutch part)' },
  { v: 'SK', t: 'Slovakia' },
  { v: 'SI', t: 'Slovenia' },
  { v: 'SB', t: 'Solomon Islands' },
  { v: 'SO', t: 'Somalia' },
  { v: 'ZA', t: 'South Africa' },
  { v: 'GS', t: 'South Georgia and the South Sandwich Islands' },
  { v: 'KR', t: 'South Korea' },
  { v: 'SS', t: 'South Sudan' },
  { v: 'ES', t: 'Spain' },
  { v: 'LK', t: 'Sri Lanka' },
  { v: 'SD', t: 'Sudan' },
  { v: 'SR', t: 'Suriname' },
  { v: 'SJ', t: 'Svalbard and Jan Mayen' },
  { v: 'SZ', t: 'Swaziland' },
  { v: 'SE', t: 'Sweden' },
  { v: 'CH', t: 'Switzerland' },
  { v: 'SY', t: 'Syrian Arab Republic' },
  { v: 'TW', t: 'Taiwan, Province of China' },
  { v: 'TJ', t: 'Tajikistan' },
  { v: 'TZ', t: 'Tanzania, United Republic of' },
  { v: 'TH', t: 'Thailand' },
  { v: 'TL', t: 'Timor-Leste' },
  { v: 'TG', t: 'Togo' },
  { v: 'TK', t: 'Tokelau' },
  { v: 'TO', t: 'Tonga' },
  { v: 'TT', t: 'Trinidad and Tobago' },
  { v: 'TN', t: 'Tunisia' },
  { v: 'TR', t: 'Turkey' },
  { v: 'TM', t: 'Turkmenistan' },
  { v: 'TC', t: 'Turks and Caicos Islands' },
  { v: 'TV', t: 'Tuvalu' },
  { v: 'UG', t: 'Uganda' },
  { v: 'UA', t: 'Ukraine' },
  { v: 'AE', t: 'United Arab Emirates' },
  { v: 'GB', t: 'United Kingdom' },
  { v: 'US', t: 'United States' },
  { v: 'UY', t: 'Uruguay' },
  { v: 'UZ', t: 'Uzbekistan' },
  { v: 'VU', t: 'Vanuatu' },
  { v: 'VE', t: 'Venezuela, Bolivarian Republic of' },
  { v: 'VN', t: 'Vietnam' },
  { v: 'VI', t: 'Virgin Islands' },
  { v: 'WF', t: 'Wallis and Futuna' },
  { v: 'EH', t: 'Western Sahara' },
  { v: 'YE', t: 'Yemen' },
  { v: 'ZM', t: 'Zambia' },
  { v: 'ZW', t: 'Zimbabwe' },
]

const timezones = [
  {
    o: '-39600',
    v: 'International Date Line West',
    t: '(GMT-11:00) International Date Line West',
  },
  { o: '-39600', v: 'Midway Island', t: '(GMT-11:00) Midway Island' },
  { o: '-39600', v: 'Samoa', t: '(GMT-11:00) Samoa' },
  { o: '-36000', v: 'Hawaii', t: '(GMT-10:00) Hawaii' },
  { o: '-28800', v: 'Alaska', t: '(GMT-08:00) Alaska' },
  {
    o: '-25200',
    v: 'Pacific Time (US &amp; Canada)',
    t: '(GMT-07:00) Pacific Time (US &amp; Canada)',
  },
  { o: '-25200', v: 'Tijuana', t: '(GMT-07:00) Tijuana' },
  { o: '-25200', v: 'Arizona', t: '(GMT-07:00) Arizona' },
  {
    o: '-21600',
    v: 'Mountain Time (US &amp; Canada)',
    t: '(GMT-06:00) Mountain Time (US &amp; Canada)',
  },
  { o: '-21600', v: 'Chihuahua', t: '(GMT-06:00) Chihuahua' },
  { o: '-21600', v: 'Mazatlan', t: '(GMT-06:00) Mazatlan' },
  { o: '-21600', v: 'Saskatchewan', t: '(GMT-06:00) Saskatchewan' },
  { o: '-21600', v: 'Central America', t: '(GMT-06:00) Central America' },
  {
    o: '-18000',
    v: 'Central Time (US &amp; Canada)',
    t: '(GMT-05:00) Central Time (US &amp; Canada)',
  },
  { o: '-18000', v: 'Guadalajara', t: '(GMT-05:00) Guadalajara' },
  { o: '-18000', v: 'Mexico City', t: '(GMT-05:00) Mexico City' },
  { o: '-18000', v: 'Monterrey', t: '(GMT-05:00) Monterrey' },
  { o: '-18000', v: 'Bogota', t: '(GMT-05:00) Bogota' },
  { o: '-18000', v: 'Lima', t: '(GMT-05:00) Lima' },
  { o: '-18000', v: 'Quito', t: '(GMT-05:00) Quito' },
  {
    o: '-14400',
    v: 'Eastern Time (US &amp; Canada)',
    t: '(GMT-04:00) Eastern Time (US &amp; Canada)',
  },
  { o: '-14400', v: 'Indiana (East)', t: '(GMT-04:00) Indiana (East)' },
  { o: '-14400', v: 'Caracas', t: '(GMT-04:00) Caracas' },
  { o: '-14400', v: 'La Paz', t: '(GMT-04:00) La Paz' },
  { o: '-14400', v: 'Georgetown', t: '(GMT-04:00) Georgetown' },
  {
    o: '-10800',
    v: 'Atlantic Time (Canada)',
    t: '(GMT-03:00) Atlantic Time (Canada)',
  },
  { o: '-10800', v: 'Santiago', t: '(GMT-03:00) Santiago' },
  { o: '-10800', v: 'Brasilia', t: '(GMT-03:00) Brasilia' },
  { o: '-10800', v: 'Buenos Aires', t: '(GMT-03:00) Buenos Aires' },
  { o: '-9000', v: 'Newfoundland', t: '(GMT-02:30) Newfoundland' },
  { o: '-7200', v: 'Greenland', t: '(GMT-02:00) Greenland' },
  { o: '-7200', v: 'Mid-Atlantic', t: '(GMT-02:00) Mid-Atlantic' },
  { o: '-3600', v: 'Cape Verde Is.', t: '(GMT-01:00) Cape Verde Is.' },
  { o: '0', v: 'Azores', t: '(GMT) Azores' },
  { o: '0', v: 'Monrovia', t: '(GMT) Monrovia' },
  { o: '0', v: 'UTC', t: '(GMT) UTC' },
  { o: '3600', v: 'Dublin', t: '(GMT+01:00) Dublin' },
  { o: '3600', v: 'Edinburgh', t: '(GMT+01:00) Edinburgh' },
  { o: '3600', v: 'Lisbon', t: '(GMT+01:00) Lisbon' },
  { o: '3600', v: 'London', t: '(GMT+01:00) London' },
  { o: '3600', v: 'Casablanca', t: '(GMT+01:00) Casablanca' },
  { o: '3600', v: 'West Central Africa', t: '(GMT+01:00) West Central Africa' },
  { o: '7200', v: 'Belgrade', t: '(GMT+02:00) Belgrade' },
  { o: '7200', v: 'Bratislava', t: '(GMT+02:00) Bratislava' },
  { o: '7200', v: 'Budapest', t: '(GMT+02:00) Budapest' },
  { o: '7200', v: 'Ljubljana', t: '(GMT+02:00) Ljubljana' },
  { o: '7200', v: 'Prague', t: '(GMT+02:00) Prague' },
  { o: '7200', v: 'Sarajevo', t: '(GMT+02:00) Sarajevo' },
  { o: '7200', v: 'Skopje', t: '(GMT+02:00) Skopje' },
  { o: '7200', v: 'Warsaw', t: '(GMT+02:00) Warsaw' },
  { o: '7200', v: 'Zagreb', t: '(GMT+02:00) Zagreb' },
  { o: '7200', v: 'Brussels', t: '(GMT+02:00) Brussels' },
  { o: '7200', v: 'Copenhagen', t: '(GMT+02:00) Copenhagen' },
  { o: '7200', v: 'Madrid', t: '(GMT+02:00) Madrid' },
  { o: '7200', v: 'Paris', t: '(GMT+02:00) Paris' },
  { o: '7200', v: 'Amsterdam', t: '(GMT+02:00) Amsterdam' },
  { o: '7200', v: 'Berlin', t: '(GMT+02:00) Berlin' },
  { o: '7200', v: 'Bern', t: '(GMT+02:00) Bern' },
  { o: '7200', v: 'Rome', t: '(GMT+02:00) Rome' },
  { o: '7200', v: 'Stockholm', t: '(GMT+02:00) Stockholm' },
  { o: '7200', v: 'Vienna', t: '(GMT+02:00) Vienna' },
  { o: '7200', v: 'Cairo', t: '(GMT+02:00) Cairo' },
  { o: '7200', v: 'Harare', t: '(GMT+02:00) Harare' },
  { o: '7200', v: 'Pretoria', t: '(GMT+02:00) Pretoria' },
  { o: '10800', v: 'Bucharest', t: '(GMT+03:00) Bucharest' },
  { o: '10800', v: 'Helsinki', t: '(GMT+03:00) Helsinki' },
  { o: '10800', v: 'Kiev', t: '(GMT+03:00) Kiev' },
  { o: '10800', v: 'Kyiv', t: '(GMT+03:00) Kyiv' },
  { o: '10800', v: 'Riga', t: '(GMT+03:00) Riga' },
  { o: '10800', v: 'Sofia', t: '(GMT+03:00) Sofia' },
  { o: '10800', v: 'Tallinn', t: '(GMT+03:00) Tallinn' },
  { o: '10800', v: 'Vilnius', t: '(GMT+03:00) Vilnius' },
  { o: '10800', v: 'Athens', t: '(GMT+03:00) Athens' },
  { o: '10800', v: 'Istanbul', t: '(GMT+03:00) Istanbul' },
  { o: '10800', v: 'Minsk', t: '(GMT+03:00) Minsk' },
  { o: '10800', v: 'Jerusalem', t: '(GMT+03:00) Jerusalem' },
  { o: '10800', v: 'Moscow', t: '(GMT+03:00) Moscow' },
  { o: '10800', v: 'St. Petersburg', t: '(GMT+03:00) St. Petersburg' },
  { o: '10800', v: 'Volgograd', t: '(GMT+03:00) Volgograd' },
  { o: '10800', v: 'Kuwait', t: '(GMT+03:00) Kuwait' },
  { o: '10800', v: 'Riyadh', t: '(GMT+03:00) Riyadh' },
  { o: '10800', v: 'Nairobi', t: '(GMT+03:00) Nairobi' },
  { o: '10800', v: 'Baghdad', t: '(GMT+03:00) Baghdad' },
  { o: '14400', v: 'Abu Dhabi', t: '(GMT+04:00) Abu Dhabi' },
  { o: '14400', v: 'Muscat', t: '(GMT+04:00) Muscat' },
  { o: '14400', v: 'Baku', t: '(GMT+04:00) Baku' },
  { o: '14400', v: 'Tbilisi', t: '(GMT+04:00) Tbilisi' },
  { o: '14400', v: 'Yerevan', t: '(GMT+04:00) Yerevan' },
  { o: '16200', v: 'Tehran', t: '(GMT+04:30) Tehran' },
  { o: '16200', v: 'Kabul', t: '(GMT+04:30) Kabul' },
  { o: '18000', v: 'Ekaterinburg', t: '(GMT+05:00) Ekaterinburg' },
  { o: '18000', v: 'Islamabad', t: '(GMT+05:00) Islamabad' },
  { o: '18000', v: 'Karachi', t: '(GMT+05:00) Karachi' },
  { o: '18000', v: 'Tashkent', t: '(GMT+05:00) Tashkent' },
  { o: '19800', v: 'Chennai', t: '(GMT+05:30) Chennai' },
  { o: '19800', v: 'Kolkata', t: '(GMT+05:30) Kolkata' },
  { o: '19800', v: 'Mumbai', t: '(GMT+05:30) Mumbai' },
  { o: '19800', v: 'New Delhi', t: '(GMT+05:30) New Delhi' },
  {
    o: '19800',
    v: 'Sri Jayawardenepura',
    t: '(GMT+05:30) Sri Jayawardenepura',
  },
  { o: '20700', v: 'Kathmandu', t: '(GMT+05:45) Kathmandu' },
  { o: '21600', v: 'Astana', t: '(GMT+06:00) Astana' },
  { o: '21600', v: 'Dhaka', t: '(GMT+06:00) Dhaka' },
  { o: '21600', v: 'Almaty', t: '(GMT+06:00) Almaty' },
  { o: '21600', v: 'Urumqi', t: '(GMT+06:00) Urumqi' },
  { o: '23400', v: 'Rangoon', t: '(GMT+06:30) Rangoon' },
  { o: '25200', v: 'Novosibirsk', t: '(GMT+07:00) Novosibirsk' },
  { o: '25200', v: 'Bangkok', t: '(GMT+07:00) Bangkok' },
  { o: '25200', v: 'Hanoi', t: '(GMT+07:00) Hanoi' },
  { o: '25200', v: 'Jakarta', t: '(GMT+07:00) Jakarta' },
  { o: '25200', v: 'Krasnoyarsk', t: '(GMT+07:00) Krasnoyarsk' },
  { o: '28800', v: 'Beijing', t: '(GMT+08:00) Beijing' },
  { o: '28800', v: 'Chongqing', t: '(GMT+08:00) Chongqing' },
  { o: '28800', v: 'Hong Kong', t: '(GMT+08:00) Hong Kong' },
  { o: '28800', v: 'Kuala Lumpur', t: '(GMT+08:00) Kuala Lumpur' },
  { o: '28800', v: 'Singapore', t: '(GMT+08:00) Singapore' },
  { o: '28800', v: 'Taipei', t: '(GMT+08:00) Taipei' },
  { o: '28800', v: 'Perth', t: '(GMT+08:00) Perth' },
  { o: '28800', v: 'Irkutsk', t: '(GMT+08:00) Irkutsk' },
  { o: '28800', v: 'Ulaan Bataar', t: '(GMT+08:00) Ulaan Bataar' },
  { o: '32400', v: 'Seoul', t: '(GMT+09:00) Seoul' },
  { o: '32400', v: 'Osaka', t: '(GMT+09:00) Osaka' },
  { o: '32400', v: 'Sapporo', t: '(GMT+09:00) Sapporo' },
  { o: '32400', v: 'Tokyo', t: '(GMT+09:00) Tokyo' },
  { o: '32400', v: 'Yakutsk', t: '(GMT+09:00) Yakutsk' },
  { o: '34200', v: 'Darwin', t: '(GMT+09:30) Darwin' },
  { o: '34200', v: 'Adelaide', t: '(GMT+09:30) Adelaide' },
  { o: '36000', v: 'Canberra', t: '(GMT+10:00) Canberra' },
  { o: '36000', v: 'Melbourne', t: '(GMT+10:00) Melbourne' },
  { o: '36000', v: 'Sydney', t: '(GMT+10:00) Sydney' },
  { o: '36000', v: 'Brisbane', t: '(GMT+10:00) Brisbane' },
  { o: '36000', v: 'Hobart', t: '(GMT+10:00) Hobart' },
  { o: '36000', v: 'Vladivostok', t: '(GMT+10:00) Vladivostok' },
  { o: '36000', v: 'Guam', t: '(GMT+10:00) Guam' },
  { o: '36000', v: 'Port Moresby', t: '(GMT+10:00) Port Moresby' },
  { o: '36000', v: 'Solomon Is.', t: '(GMT+10:00) Solomon Is.' },
  { o: '39600', v: 'Magadan', t: '(GMT+11:00) Magadan' },
  { o: '39600', v: 'New Caledonia', t: '(GMT+11:00) New Caledonia' },
  { o: '43200', v: 'Fiji', t: '(GMT+12:00) Fiji' },
  { o: '43200', v: 'Kamchatka', t: '(GMT+12:00) Kamchatka' },
  { o: '43200', v: 'Marshall Is.', t: '(GMT+12:00) Marshall Is.' },
  { o: '43200', v: 'Auckland', t: '(GMT+12:00) Auckland' },
  { o: '43200', v: 'Wellington', t: '(GMT+12:00) Wellington' },
  { o: '46800', v: "Nuku'alofa", t: "(GMT+13:00) Nuku'alofa" },
]

export {
  vendor_binaries,
  predefined_settings,
  php_versions,
  web_application_stacks,
  web_environments,
  web_ssl_methods,
  webservers,
  databases,
  database_encodings,
  countries,
  timezones,
}
